.TH FETCH 1
.SH NAME
fetch \- Download files form HTTP/FTP direct links
.SH SYNOPSIS
.B fetch
.I http://mydomain.com/myfile1.zip http://mydomain.com/myfile2.zip
  Download one or more files.

.B fetch
.I links.txt
  Download a list of links from a file

.SH DESCRIPTION
.I  Fetch
is a program to download files from HTTP/FTP direct link.

.SH "COPYRIGHT NOTICE"
Copyright \(co 2011 Tuan Anh Tran
